DeepLink-org/deeplink.framework

scripts/autogen_diopi_wrapper/diopi_functions.yaml
camb convolution backward return empty tensor if needed
=> feature: camb-convolution-backward-return-empty-tensor-if-needed

scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py, scripts/autogen_diopi_wrapper/diopi_functions.yaml, scripts/ci/camb/ci_camb_env.sh, torch_dipu/csrc_dipu/diopirt/diopi_helper.cpp, torch_dipu/csrc_dipu/diopirt/diopirt_impl.cpp
* fix build error when using the new diopi, where the constructor of diopiSize_t is deleted.
* Add 4 operators (normal_, random_.from, uniform_, add.out) to fallback to CPU
=> yb/fix build error of constructing diopiSize_t

setup.py
setup.py里在import不到torch的时候有一个奇怪的try except（我猜可能是为了处理这里的报错 https://github.com/pytorch/pytorch/blob/v2.0.0/torch/__init__.py#L443 ），但是问题是如果环境里就是import不到torch的话就会导致拿到的include_dirs有问题，然后会在编译extension的时候报找不到头文件，比较难以发现问题的原因。除了去掉try except这里也可以考虑改成except ImportError
get_pytorch_dir函数看起来是从https://github.com/Ascend/pytorch/blob/d6623f2f5b9f592c6a2665aec840231b08e7e5be/setup.py#L95 借鉴的
=> fix a bug of setup.py when torch can't be imported

scripts/op_capture/op_capture.py
1. Fix the bug that the data captured when there are floating-point numbers represented by scientific notation in the parameter is wrong
[dipu_ops.csv](https://github.com/DeepLink-org/DIPU/files/12513880/dipu_ops.csv)
=> fix op_capture bug

torch_dipu/__init__.py
The calling method of is_cuda in pytorch is a.is_cuda.
dipu should be consistent with this usage
=> Change the is_cuda method to property to imitate native pytorch behavior

dipu/torch_dipu/profiler/profiler.py
从原生的torch profiler 获取stack信息
开启方法如下：
with profile(record_shapes=True, with_stack=True,  experimental_config=torch._C._profiler._ExperimentalConfig(verbose=True)) as prof:
’‘’需要记录的操作‘’‘
print(prof.key_averages(group_by_stack_n=5))
prof.export_chrome_trace('result_pytorch_dipu_with_stack.json')
获得结果如下：
=> add stack info

dipu/tests/test_ops/archived/test_SyncBN.py, dipu/tests/test_ops/archived/test_storage.py, dipu/torch_dipu/__init__.py
pytorch的is_cuda不是一个函数调用是一个属性调用
a = torch.tensor([2.2,13])
print(a.is_cuda)
DIPU是函数调用形式
print(a.is_cuda())
通过把函数改写为属性解决这个问题
解决办法from @wey-code 
-----------------------
Previously, there was a problem with the input data structure（count_all）of test_batch_norm_gather_stats_with_counts, which would cause the test to fail on camb. This PR fixes the problem.
=> fix bug for is_cuda and fix syncbn test case

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
test_erfinv.py missed `assert` so this error is not detected. The updated test is not uploaded since I am rewriting all tests.
=> fix bind error of erfinv: diopiErf -> diopiErfinv

dipu/CMakeLists.txt
检测pytorch编译时abi使用版本，使得dipu编译时和pytorch编译的abi版本一致。
用于解决conda install问题。
=> add abi version detection

dipu/tests/test_ops/archived/test_autocast.py, dipu/torch_dipu/__init__.py, dipu/torch_dipu/dipu/amp.py
用于修改在a100及以上不能跑bf16的问题，让dipu在cuda上的行为和默认保持一致
同时将DIPU的默认dtype从bf16修改为fp16，避免一些厂商不支持bf16的问题。
=> If vendor is cuda, its ability to support bf16 remains the same as the default.

dipu/CMakeLists.txt
DIOPI_PATH can be changed in CMAKE
=> changing Cmake

dipu/CMakeLists.txt, dipu/QuickStart.md, dipu/scripts/ci/ascend/ci_ascend_env.sh, dipu/scripts/ci/camb/ci_camb_env.sh, dipu/scripts/ci/camb/ci_camb_script.sh, dipu/scripts/ci/nv/ci_nv_env.sh, dipu/scripts/ci/nv/ci_nv_script.sh, dipu/scripts/ci/topsrider/ci_topsrider_env.sh, dipu/setup.py, dipu/template_build_sh, dipu/tests/cpp/CMakeLists.txt, dipu/torch_dipu/csrc_dipu/CMakeLists.txt
- 将编译好的 DIOPI 以 imported 形式引入，可以以 WITH_DIOPI 的 CMake 参数设置位置（一般默认值就能用）
- (in future PR) 将支持 WITH_DIOPI=internal 来就地编译 DIOPI
- 删除所有 LIBRARY_PATH 的需求（会影响 rpath），并正确设置 DIOPI 和 DIPU 的 rpath
- 删除对 DIOPI LD_LIBRARY_PATH 的需求（由 rpath 寻找），因此总是可以正确找到编译 DIPU 时用的版本
- 修复并优化 cpp test 的 CMake
- 格式化所有受影响的 CMake
- 将一些非 DIPU 的 include dir 设置为 isystem
=> (lljbash) CMake 优化

dipu/tests/python/unittests/test_random.py
see https://github.com/DeepLink-org/DIOPI/pull/487
=> Remove @skipOn("MLU") in test_random.py since the bug has been fix

dipu/torch_dipu/csrc_dipu/CMakeLists.txt
This PR is discussed with DICP team and the purpose is let DIPU compatible with DICP when building.
Please refer to the feishu doc "DICP接入DIPU"
=> rewrite the way of linking libdiopi_impl.so in CMake for DICP

dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
There is a default low-priority fallback function, so there is no need to register a high-priority fallback.
=> fix no need fallback function register

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
convnext perf issue: do not register linear and linear_backward, pytroch will compute linear and its backward under graph mech
=> fix linear for perf of convnext

dipu/torch_dipu/csrc_dipu/vendor/topsrider/TopsGeneratorImpl.cpp
Remove the function "init_state" from TopsGeneratorImpl.cpp because it has already been deleted in the parent class.
=> Remove the function "init_state" from TopsGeneratorImpl.cpp

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
diopiMatmul平台适配，使得s2生成并注册、其他device不生成，解决原来s2上fallback到cpu的问题
=> matmul device adapter

dicp/dicp/vendor/AscendGraph/conversion.py
=> refact dynamic_shape

dipu/setup.py
在 dipu 的 setup.py 中增加了通过环境变量 `DIPU_WITH_DIOPI_LIBRARY` 修改 CMakeLists.txt 中的变量 `WITH_DIOPI_LIBRARY`。如此修改可以在燧原平台上编译无 diopi_impl 依赖的 torch_dipu ，以便后续 dicp 的 ci 搭建。
=> add DIPU_WITH_DIOPI_LIBRARY env option in dipu/setup.py

dicp/dicp/dynamo_bridge/op_transformer.py, dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py, dicp/dicp/vendor/AscendGraph/conversion.py, dicp/dicp/vendor/AscendGraph/opset_convert.py
Fix hf llama precision for ascend backend.
=> Fix hf llama precision.

dipu/.clang-tidy, dipu/.clangd, dipu/third_party/CMakeLists.txt, dipu/torch_dipu/csrc_dipu/CMakeLists.txt
1. 为 DIPU 仓库添加一个 `.clang-tidy` 文件，待问题修正之后，再修改 CI 等配置
2. 重构 (简化) 了 kineto 的引入方式，尝试修复 libfmt 的编译时机的问题
=> [dipu] Add .clang-tidy

dicp/dicp/vendor/TopsGraph/codegen/src/common_ops.cpp, dicp/test/model/test_resnet50.py
batchnorm 需要 type 来避免编译期出错。虽然这个错误看上去不影响正确性。但是会出现error
=> [dicp][tops] Fix BatchNorm in resnet50.

dipu/scripts/ci/ascend/ci_ascend_script.sh, dipu/scripts/ci/camb/ci_camb_script.sh, dipu/scripts/ci/droplet/ci_droplet_script.sh, dipu/scripts/ci/nv/ci_nv_script.sh, dipu/scripts/ci/topsrider/ci_topsrider_script.sh
原先CI在build dipu失败时是成功退出，继续执行下面的job，原因为：默认情况下，管道命令的返回值是最后一个命令的退出状态【原始脚本中在管道后采用了tee命令，触发了bug】。启用`pipefail`选项后，管道命令的返回值将变为其中任何一个命令失败时的返回值（即最左边的非零退出状态），这有助于检测和处理管道中间某个命令的错误。
=> [DIPU]Wx/check the status of build dipu

dipu/CMakeLists.txt, dipu/torch_dipu/csrc_dipu/vendor/supa/copyinplace.cpp, dipu/torch_dipu/csrc_dipu/vendor/supa/deviceimpl.cpp
fix virtual memory error of using SUPA
=> [FIX] fix virtual memory error of using SUPA

dipu/SupportedDiopiFunctions.txt, dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
Reduced ~5% training time in torchvision ResNet-18 (batch_size=1).
=> [dipu] Speedup `dumpOnArgLevel()` by using lazy initialization

dicp/dicp/dynamo_bridge/op_transformer.py, dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py, dicp/dicp/vendor/AscendGraph/conversion.py
优化 ascend graph llama finetune 性能
- 在dicp ascend 中融合 transpse/mm
- 在load_and_run 中，公用同一个zero_tensor
new feature
=> [DICP]fuse transpose/mm in ascendgraph

dipu/.clang-tidy, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h, dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp, dipu/torch_dipu/csrc_dipu/vendor/cuda/deviceimpl.cpp
Slight improvement on ops like `empty`.
ResNet-18 (batch_size=1, iter=1000) 19.7s->19.6s
=> [dipu] Optimize `getAllocator` by adopting lookup table

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/scripts/autogen_diopi_wrapper/diopi_wrapper_template.py, dipu/tests/python/unittests/test_prod.py
`prod` (and other reduction ops) should promote int type (including `bool`) to `int64` when `dtype` is not explicitly provided.
Only `prod` (without `dim`) should be taken care of in DIPU, because the other cases are already correctly handled in PyTorch.
=> [dipu] fix: `torch.prod` int type promotion

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
disable autocompare for _amp_foreach_non_finite_check_and_unscale_
=> disable autocompare for _amp_foreach_non_finite_check_and_unscale_

dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp, dipu/torch_dipu/csrc_dipu/base/basedef.h, dipu/torch_dipu/csrc_dipu/profiler/profiler.h, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUEvent.h, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStream.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStream.h, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h, dipu/torch_dipu/csrc_dipu/runtime/core/guardimpl/DIPUGuardImpl.h, dipu/torch_dipu/csrc_dipu/runtime/distributed/DICLUtils.hpp, dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.cpp
本次 PR 涉及到两个修改：
1. 删除 `DIPUStream` 的无用接口，对部分接口新增 explicit 限制
2. 将 `DIPUStream.cpp` 中的部分全局变量重构为 static 函数内的 static 变量
=> [DIPU] Move static global variables into static functions.

dipu/tests/python/individual_scripts/test_dipu_profiler.py, dipu/tests/python/individual_scripts/test_profiler_communication.py, dipu/tests/python/unittests/test_profiler.py, dipu/tests/python/unittests/test_profiler_cuda.py, dipu/torch_dipu/profiler/profiler.py
1. 采集到的数据跟原生差异大，性能分析的时候不容易对齐
2. profiler开销较大，每次kernel调用前后插入两个event的方式
1. nv上默认使用torch profiler，同时支持环境变量切换到dipu profiler
2. 其他厂商也会推进接入厂商的profiler api
=> [DIPU]support using torch profiler on nv

dipu/scripts/ci/nv/ci_nv_env.sh
remove useless LD_PRELOAD env, causing trouble
```bash
/mnt/cache/share/platform/env/miniconda3.10/envs/pt2.0_diopi/bin/gdb: /mnt/cache/share/platform/dep/gcc-10.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /mnt/cache/share/platform/env/miniconda3.10/envs/pt2.0_diopi/bin/gdb)
/mnt/cache/share/platform/env/miniconda3.10/envs/pt2.0_diopi/bin/gdb: /mnt/cache/share/platform/dep/gcc-10.2/lib64/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /mnt/cache/share/platform/env/miniconda3.10/envs/pt2.0_diopi/bin/gdb)
```
=> remove useless LD_PRELOAD

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/tests/python/unittests/test_layer_norm.py
把layer_norm构造的output的format和pytorch对齐 
https://github.com/pytorch/pytorch/blob/v2.0.0/aten/src/ATen/native/cuda/layer_norm_kernel.cu#L1340-L1346
=> change layer_norm's output format to align torch

dipu/torch_dipu/__init__.py
目前dipu不支持 jit  之前是什么也不做，这样如果有模型使用jit 那么会在适配时得到none type， 现在改为返回原object，虽然不能加速但是不影响原本功能
=> [dipu]Make a fake jit in which just return orginal object

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctions.hpp
给droplet加一下matmul_backward的注册，这个暂时不太好加测例，我自测了些情况fallback函数是可以正常工作的，diopi应该可以先不更新，或者等那边的合了之后再更新下
diopi对应修改：https://github.com/DeepLink-org/DIOPI/pull/828
=> [dipu]add matmul_backward for droplet

dipu/scripts/ci/ci_one_iter.sh
数据集统一迁移至各集群/mnt/lustre/share_data/PAT/datasets，修改对应ci_one_iter.sh下的路径
=> [DIPU]modify sourcepath for dataset migration

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
yolov5八卡性能提升至0.298329 / iter，相较pytorch性能从77.3%提升到77.4%
=> [dipu]ywt/feature: optimize indexput

dipu/tests/python/individual_scripts/test_dipu_fallback.py, dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp, dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
**Motivation and Context  背景**
-   由于dipu存在自定义的dispatch逻辑(包括custom_fallback)，影响了dynamo中对meta key的dispatch行为，在linear设为custom_fallback后，会影响linear_backward的dispatch行为。
**Description  描述  功能抽象**
-   通过增设一个环境变量DIPU_DISABLE_CUSTOM_FALLBACK以及disable_custom_fallback_ops_list在必要时禁用custom_fallback的逻辑（默认开启custom_fallback）。
**类别 （Bug 修复|new feature| Intenal SW ）**
- Bug 修复
=> [DIPU] disable custom fallback ops partly.

dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/conversion.py, dicp/test/ascend_scripts/ops/static.ini, dicp/test/op/test_ge.py, dicp/test/op/test_logical_or.py, dicp/test/op/test_tril.py
在dicp ascend 新增 repeat/tril/ge/logical_or 算子
在dicp ascend 新增 repeat/tril/ge/logical_or 算子
new feature
=> [DICP] add repeat/tril/logical_or/ge for ascendgraph

dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/conversion.py, dicp/dicp/vendor/AscendGraph/pattern_replacement.py, dicp/test/ascend_scripts/ops/static.ini, dicp/test/op/test_index_put.py, dicp/test/op/test_repeat_interleave.py, dicp/test/op/test_slice_scatter.py
为实现 dicp ascend 对于 lightllm llama2 量化推理的支持，实现三个算子。
在 dicp ascend 支持 aten 的`index_put.default`, `repeat_interleave.self_int` 和 `slice_scatter.default` 算子。
new feature
=> [dicp] add ascendgraph index_put, repeat_interleave, slice_scatter

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
尝试修复一个问题。当前 GroupNorm 使用了固定的 float32 类型作为均值、方差等返回值，这里复用了 torch 的判断逻辑处理 fp16 及混合精度的类型。
参考：[`mixed_data_type.h`](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cpu/mixed_data_type.h)
=> [DIPU] Use mixed scalar type instead of f32 in group_norm.

dicp/dicp/dynamo_bridge/graph.py, dicp/dicp/vendor/AscendGraph/conversion.py, dicp/dicp/vendor/AscendGraph/opset_convert.py, dicp/test/ascend_scripts/ops/static.ini, dicp/test/op/test_scalar_tensor.py
在dicp ascend 新增 scalar_tensor 算子
在dicp ascend 新增 scalar_tensor 算子
new feature|
=> [DICP] add scalar_tensor for ascendgraph

.github/workflows/format.yml, .github/workflows/main.yml, dipu/.clang-tidy, dipu/.clangd, dipu/SupportedDiopiFunctions.txt, dipu/scripts/ci/nv/ci_nv_tidy.sh
- 在 CI 流程中检查大家是否忘记提交自己的 `SupportedDiopiFunctions.txt` 文件
- 已测试 `SupportedDiopiFunctions.txt` 不一致时会正常报错
- 试了一下 clang17，这个版本新增了缺少或者多余的头文件的检查（iwyu），挺实用的
- 目前 clang16 到 clang17 不需要修改代码，我把新增的检查都关了，之后逐渐开放吧
- 顺便优化了一下之前的脚本
- 移除 subshell
- 简化部分写法
- 顺便吐槽一下 git 版本太老了，甚至不支持 `-C` 之类的参数
=> [DIPU] Check SupportedDiopiFunctions.txt and upgrade to clang17

dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
NAN and INF values on Ascend are not correctly handled as torch.nan and torch.inf since the overflow mode is set to saturation (0) by default.
Setting ACL_RT_OVERFLOW_MODE to INFNAN can resolve this issue, which has been verified on diopi_test.
Example:
Before changes (float16 INF):
```
tensor(65504., device='cuda', dtype=torch.float16)
```
After changes (float16 INF):
```
tensor(inf, device='cuda', dtype=torch.float16)
```
=> [DIPU] set ACL_RT_OVERFLOW_MODE to INFNAN for Ascend

dipu/.clang-tidy, dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/torch_dipu/csrc_dipu/aten/ops/NodispatchUtils.hpp
| model            | pytorch | dipu before  | dipu after   | speedup |
|------------------|---------|--------------|--------------|---------|
| resnet18-bs1-fwd | 3.0ms   | 4.1ms(73.2%) | 3.8ms(78.9%) | 7.9%    |
| llama7b-eval-fwd | 70ms    | 94ms(74.5%)  | 94ms(74.5%)  | 0       |
=> [dipu] perf: use nodispatch::empty and nodispatch::empty_like to eliminate the dispatch of empty

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
nonzero and index.Tensor_out are both synchronous ops, which is guaranteed by the low-level (DIOPI) implementation. Hence the sync in DIPU is unnecessary.
=> [DIPU] Remove unnecessary sync for nonzero and index.Tensor_out

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
- Scalar checks in diopi_functions.yaml (AutoGenedKernels.cpp) are updated to align with [PyTorch](https://github.com/pytorch/pytorch/blob/fad228c7cc3d954d78abf009f469c5befc950d3a/c10/core/TensorImpl.h#L1307-L1321)
- Optimize the add op for cases where `other` is a scalar on device. Previous code resulted in unnecessary copys between host and device and synchronization.
=> [DIPU] Fix scalar checks in diopi_functions.yaml and optimize the add op for scalar inputs

.github/workflows/main.yml, dipu/CMakeLists.txt, dipu/tests/python/individual_scripts/test_op_benchmark.py, dipu/tests/python/unittests/test_profiler_vendor.py, dipu/torch_dipu/csrc_dipu/aten/ops/DIPUAmp.cpp, dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUGeneratorImpl.h, dipu/torch_dipu/csrc_dipu/utils/helpfunc.hpp, dipu/torch_dipu/csrc_dipu/vendor/cuda/patch/DIPUPatchCudaAllocator.cpp, dipu/torch_dipu/dipu/__init__.py, dipu/torch_dipu/dipu/utils.py, dipu/torch_dipu/testing/_internal/common_utils.py
1. dipu 支持了 torch 2.1.0. 由于时间原因， 测例没有同步加上。
但是本地测了 dipu camb下面python/run_tests.sh 的测试 （也就是我们自己写的单测）， pytoch的 单测和 oneiter 未测试。
测试结论：camb下的 profiler 无法工作， 打印错误堆栈的时候似乎又触发了其他错误，然后无限循环栈溢出了。 其他测试均正常通过。
其中一个 profiler的 测例 加了 新的 skip， 在 torch 2.1.0 下可以跳过。 另外2个 profiler的测例也有类似问题， 因为是自动生成的， 所以没处理
=> support dipu use torch2.1.0

dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.cpp, dipu/torch_dipu/csrc_dipu/vendor/ascend/communicatorimpl.cpp, dipu/torch_dipu/dipu/amp.py
support bfloat16 dtype
update:
hcclDataTypes definition
_local_scalar_dense_dipu impl
is_bf16_supported impl
=> [Ascend] fuj / support bfloat16 dtypes for ascend

dipu/CMakeLists.txt
See also: https://cmake.org/cmake/help/latest/policy/CMP0094.html
close #322
=> fix(dipu): let CMake choose current python in PATH rather than highest version

dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.cpp, dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp, dipu/torch_dipu/csrc_dipu/vendor/ascend/AscendCopyInplace.cpp, dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
According to our benchmark for H2D/D2H synchronous direct memory copy, (Sync + memCopySync) is faster than (memCopyAsync + Sync) on Ascend. Hence we replace the former strategy (the default one) with the latter in this PR.
=> [DIPU] Replace the default (memCopyAsync + Sync) strategy with (Sync + memCopySync) for direct memory copy on Ascend

dipu/SupportedDiopiFunctions.txt, dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/tests/python/unittests/test_ones.py, dipu/tests/python/unittests/test_zeros.py
add ones/zeros/zero_ op
before:
after:
=> feat(dipu): add schema: ones/zeros/zero_

dipu/torch_dipu/csrc_dipu/aten/ops/AutoCompareUtils.hpp, dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
This happens when DIPU_DUMP_OP_ARGS is set to 3, and the tensor is copied from device to CPU before dumping the tensor.
This patch uses a function previously used in auto_compare (renamed to `toCpuTensorWithoutDiopiCopy()`) to avoid the infinite recursion.
=> fix(dipu): avoid infinite recursion in `dumpArg()`

dipu/.clang-format, dipu/tests/python/unittests/test_python_device.py, dipu/torch_dipu/csrc_dipu/binding/patchCsrcDevice.cpp
Example:
```python
import torch
import torch_dipu
torch.cuda.set_device(0)
a = torch.tensor([1, 2, 3]).cuda()
print(a)
```
Expected output:
```
tensor([1, 2, 3], device='cuda:0')
```
Current output (before this commit):
```
tensor([1, 2, 3], device='cuda')
```
=> fix(dipu,python): print device index for cuda tensor

dipu/torch_dipu/csrc_dipu/vendor/droplet/deviceimpl.cpp
cannot reuse DIPU_CALLDROPLET due to special handling of NotReady
```cpp
#define DIPU_CALLDROPLET(Expr)                                            \
{                                                                       \
tangError_t ret = Expr;                                               \
if (ret != tangSuccess) {                                             \
printf("call a tangrt function (%s) failed. return code=%d", #Expr, \
ret);                                                        \
throw std::runtime_error("dipu device error");                      \
}                                                                     \
}
```
=> feat(dipu,droplet): add error message when tangEventQuery failed

dipu/torch_dipu/dipu/__init__.py
- Fixed a memory leak caused by the continuous increase of the `lazy_call` queue. See `ModelLink_Ascend/ascendspeed/core/tensor_parallel/random.py:_set_cuda_rng_state` for more details
- Fixed a precision error where setting the RNG state was never executed. If not fixed, during the backward checkpoint, the RNG state was not consistent with the forward state.
=> ywt/fix: memory leak and precision error

dipu/torch_dipu/csrc_dipu/vendor/cuda/communiatorimpl.cpp
之前用的两个宏 NCCL_HAS_AVG 和 HAS_NCCL_BF16_DATATYPE 是在 torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp 和 torch/csrc/cuda/nccl.h 中定义的，但是这两个文件都是 torch 的源码，在 dipu 里看不到。所以将这两个宏定义抄到了 dipu 的代码中。
=> fix(dipu,cuda): add nccl capability check

dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
See also: #682
---
1. 重构，在不改变功能（不支持单进程绑定多卡，强制要求单进程只能绑定单卡，且只能绑定一次）的前提下，更清晰地定义了编程模型，降低了理解难度，便于后期维护。
2. 增强了并发时的线程安全。
=> fix(dipu,vendor,ascend): simple and thread-safe device management

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
`device: [-ascend]` should be `device: [all, -ascend]`.
顺便调整了顺序，更容易读
=> fix(dipu): fix device field of linalg_vector_norm in autogen

.github/workflows/_runs-on-nv-step1.yml, dipu/scripts/ci/nv/ci_nv_tidy.sh
虽然 clangd-tidy 仓库很小，但网络情况似乎不太好经常 clone 失败。这里新增参数，允许直接使用某个路径的 clangd-tidy
=> feat(dipu): use internal clangd-tidy when running ci

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/tests/python/unittests/test_upsample.py
S2 的一些 DIOPI 实现未考虑到输入输出 memory_format 不一致的情况，也没有接入 adaptor， 导致在某些情况下会出现结果错误。
PyTorch 默认会根据输入的 memory_format 来选择输出的 memory_format。在我们自己注册的 functional 算子中，我们也需要根据输入的 memory_format 来选择输出的 memory_format。此前，使用 empty_like 的代码都不会有问题， 但是 empty 的代码中，我们使用了 c10::nullopt 来表示没有指定 memory_format。这是因为我们误认为前面传入的 options 会包含 memory_format，但实际上并不包含（这是 torch 将 options 既用于 config 又用于 attr 导致的误解）。因此，我们需要使用 input.suggest_memory_format() 来获取输入的 memory_format。
（TODO）本次 PR 更改了与 adaptor 优化相关的代码。我预计还有许多其他地方也需要修改。此外，inferer 可能也要考虑到这个问题。
（TODO）这样也无法保证 out 算子能正确运行，长期看需要把 S2 接进 adaptor。
=> fix(dipu): use suggest_memory_format() instead of nullopt in autogen

dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctions.hpp
=> [DIPU] Fix custom fallback for non-out ops of silu, rsqrt which lacks postprocessing conversion for out tensor

dipu/torch_dipu/csrc_dipu/base/environ.hpp, dipu/torch_dipu/csrc_dipu/runtime/device/basedef.h
gcc 7.5 对 c++17 支持不完整，暂且加了一个绕过。
**Update**：干脆直接重写了
=> refactor(dipu): redesign environ.hpp to be a better code base

dipu/torch_dipu/csrc_dipu/runtime/core/DIPUEvent.h, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUAsyncResourcePool.h, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBSCachingAllocator.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPURawCachingAllocator.cpp
- Implement a partial template specialization for AsyncResourcePoolImpl (algorithm = OneStreamOneQueueAlgo = 1) as a new implementation which provides a separate queue for each stream in the asynchronous resource pool. According to https://github.com/pytorch/pytorch/blob/03a05e791aabe4f2e3938626bff849641dc101ea/c10/cuda/CUDACachingAllocator.cpp#L2745 this implementation can avoid head-of-line delays if one or more streams has long-running operations to wait for.
- Use the new implementation in BF, BS, RAW caching allocators to replace the old implementation, which has one global queue for all streams.
- Compared to the old implementation where any event won't be returned to the event pool until all events attached to the same resource are complete, another advantage of the new …
=> [DIPU] New implementation for AsyncResourcePoolImpl providing a separate queue for each stream

dipu/tests/python/individual_scripts/test_rt_ddp.py, dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp, dipu/torch_dipu/csrc_dipu/runtime/device/diclapis.h, dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.cpp, dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.h, dipu/torch_dipu/csrc_dipu/runtime/distributed/DICLUtils.hpp, dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.cpp, dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.h, dipu/torch_dipu/csrc_dipu/vendor/ascend/communicatorimpl.cpp
增加获取当前集合通信操作所在的通信域的名称的功能，调用的cann接口为：
https://www.hiascend.com/document/detail/zh/canncommercial/80RC1/apiref/hcclapiref/hcclcpp_07_0012.html。
=> add get comm name for ascend

dipu/torch_dipu/csrc_dipu/aten/ops/NodispatchUtils.hpp, dipu/torch_dipu/csrc_dipu/diopirt/diopirt_impl.cpp
通过timeline中分析，部分算子在调用时会有一次empty kernel的调用逻辑（比如：max）。经过分析是算子需要有输出数据的时候，在deeplink.framework中会构造一个空的数据，构造过程会调用at::empty()，从而会多一次kernel调用。现通过nodispatch的empty方式，降低empty的dispatch次数。
改造前：
改造后：
=> [DIPU] change at::empty to nodispatch::empty at require tensor function

dipu/tests/python/individual_scripts/test_rt_ddp.py, dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.cpp, dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.h, dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.cpp, dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.h
在对于 lmdeploy 的支持过程中，发现 pytorch 2.0 dtensor 的 distribute_tensor 需要用到 dicl scatter 操作，lmdeploy _tp_build_model._broadcast_config 中的 dist.gather_object 需要用到 dicl gather 操作。
本 PR 使用 diclSend 和 diclRecv 实现单个 diclComm 下的 diclScatter 和 diclGather。
=> [dipu] feat: add gather and scatter support by using recv and send

dipu/third_party/CMakeLists.txt, dipu/torch_dipu/csrc_dipu/CMakeLists.txt
related：https://github.com/DeepLink-org/DIOPI/pull/1257
副作用：diopi 的 lto 模式继承了 dipu，其他的配置未见到有影响的污染
后续考虑：
- DIOPI 的 lib 位置可以考虑改动（基础设施已就位）
- 各种选项名称考虑加上前缀 DIPU DIOPI 等
=> build(dipu): make WITH_DIOPI_LIBRARY=INTERNAL really internal

dipu/tests/python/individual_scripts/test_rt_ddp.py, dipu/torch_dipu/csrc_dipu/runtime/device/diclapis.h, dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.cpp, dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.h, dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.cpp, dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.h, dipu/torch_dipu/csrc_dipu/runtime/distributed/c10dOps.cpp, dipu/torch_dipu/csrc_dipu/vendor/ascend/communicatorimpl.cpp
- Done
- Implement all_to_all_single with equal splits
- Implement all_to_all
- Leave to the future
- For cuda, use nccl group calls for all_to_all_single and all_to_all (We need to design some new APIs to support group calls)
- Implement a more performant fallback for all_to_all without using a flattened tensor for relay
=> [DIPU] Implement all_to_all_single (with unequal splits) and all_to_all

dipu/scripts/ci/ci_one_iter.sh
Update deeplinkext to fix the  compilation error.
=> [DIPU] update commit of deeplinkext

dipu/tests/python/unittests/test_copy.py, dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp, dipu/torch_dipu/csrc_dipu/vendor/ascend/AscendCopyInplace.cpp, dipu/torch_dipu/csrc_dipu/vendor/cuda/CUDACopyInplace.cpp
1. copy算子代码优化
2. 修复cuda下copy算子的bug，详见test_copy.py算子新增测例。当前non_blocking=False，cpu端的修改会影响copy到device的结果，因为copyPostProcess里面没有执行sync stream，该pr修复了这个问题
=> fix cuda copy

dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py, dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctions.hpp, dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
Use c10::DimVector instead of std::vector<int64_t> to avoid frequent allocation and release of memory on the heap
=> use c10::DimVector instread of std::vector<int64_t>

dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
设置cpu 亲和性，让特定的几个cpu使用特定加速卡，减小线程切换的开销，提高缓存命中率。默认情况下（DIPU_CPU_AFFINITY=0），会根据当前可用cpu核心数量和当前可用所有加速卡数量自动计算出每张卡使用的cpu核心数。如果用户手动设置DIPU_CPU_AFFINITY=N, 则每张卡会使用N个cpu核。
Set CPU affinity to let specific CPUs use specific accelerator cards, reduce thread switching overhead, and improve cache hit rate. By default (DIPU_CPU_AFFINITY=0), the number of CPU cores used by each card will be automatically calculated based on the number of currently available CPU cores and the number of all currently available accelerator cards. If DIPU_CPU_AFFINITY=N, each card will use N CPU cores.
=> support set cpu affinity

.github/workflows/main.yml, dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp, dipu/torch_dipu/csrc_dipu/vendor/camb/CambCopyInplace.cpp
寒武纪runtime不支持stream等待另一张卡上的event, cnrtQueueWaitNotifier 返回100050(This indicates that the feature is not supported now),因此我们这里使用同步级别更高的syncStream来代替stramWaitEvent。
由于测试用例中有些测例（多卡间内存拷贝至少需要两张卡，通信相关测例需要四张卡）需要多张卡，在ci中运行测例时，分配多张卡资源,避免有些测例被跳过
Cambrian runtime does not support stream waiting for events on another card, cnrtQueueWaitNotifier returns 100050 (This indicates that the feature is not supported now), so we use syncStream with a higher synchronization level instead of stramWaitEvent.
Because some test cases in the test case require multiple cards (memory copy between multiple cards requires at least two cards, and communication-related test cases require four cards), when running the test cases in CI, allocate multiple card resources to avoid some test cases being skipped.
=> fix camb copy_D2otherD bug

dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingDeviceAllocator.cpp
NativeCachingAllocator提前析构，导致退出的时候出现析构core dump。将NativeCachingAllocator放在堆上，进程退出的时候由操作系统回收，避免析构顺序导致的问题。
=> [DIPU]fix torch allocator core dump when process exit

dipu/tests/python/individual_scripts/test_allocator_conf.py, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingDeviceAllocator.cpp
以前会直接挂，现在强制 false。
用于 internevo 这种在代码里强设 expandable_segments 的情况。
=> feat(dipu): exit->warn when expandable_segments set but not supported

.github/workflows/_runs-on-nv-step2.yml, .github/workflows/main.yml, dipu/tests/python/individual_scripts/test_rt_ddp.py, dipu/tests/python/unittests/test_copy.py, dipu/tests/run_ascend_tests.sh, dipu/torch_dipu/csrc_dipu/CMakeLists.txt, dipu/torch_dipu/testing/_internal/common_utils.py
1. 修复cuda 多卡测试时出现的问题
2. ci中部分测试时分配多卡资源来进行多卡测试
need_two_gpus 是一个和ci 机器约定好的标识符，不是随便起的名，要改得两边同时改。目前nv的ci是跑在sensecore上的。
=> enable multi-cards relate test case

dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py, dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/torch_dipu/csrc_dipu/aten/ops/DIPUOpInferrer.cpp, dipu/torch_dipu/csrc_dipu/aten/ops/DIPUOpInferrer.h, dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
This change remove a redundency transformation mul_tensor->mul_scalar->mul_tensor. Also with a faster BinaryOpInferrer.
The aten::mul is almost as fast as torch in cpu avg.
=> perf(dipu): faster aten::mul in cuda & muxi

dipu/torch_dipu/dipu/dataloader.py
S2等没有实现pin_memory的vendor，需要在框架层对pin_memory设置为False，是不方便的。
因此在DIPU层对vendor进行判断，强行设置pin_memory为False，并打印相关LOG。
=> feat(dipu): set pin_memory to false for unsupported vendor

dipu/tests/python/unittests/test_profiler_vendor.py, dipu/torch_dipu/csrc_dipu/vendor/ascend/AscendDeviceActivity.cpp, dipu/torch_dipu/csrc_dipu/vendor/ascend/AscendDeviceActivity.h, dipu/torch_dipu/profiler/ascend/ascend_profiler_merger.py, dipu/torch_dipu/profiler/profiler.py
将DIPU ascend profiler和torch profiler对齐
- cpp层通过实现libkineto接口，调用aclprof api，在临时路径生成包含硬件统计信息的ascend PROF文件，并通过libkineto将路径传递到python层
- python层mock了torch profile中的export_chrome_trace方法，加入msprof工具解析、chrome_json合并操作
- 已在910机器上验证过单机单卡和单机多卡
```py
output_path = './example.json'
input = torch.randn(2, 3).cuda()
with profile(
activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA],
with_stack=True,
schedule=torch.profiler.schedule(wait=0, warmup=0, active=2, repeat=2)
) as prof:
for i in range(10):
y = fn(input)
z = y + y    
prof.step()
prof.export_chrome_trace(output_path)
```
=> [Feature] Align ascend profiler with torch profiler

dipu/torch_dipu/csrc_dipu/vendor/cuda/patch/DIPUPatchCudaAllocator.cpp
没有实现的Allocator Proxy被调用时，没有正常报错，会导致隐藏的错误，在函数内部设置为正确的报错。
=> fix(dipu): correctly report error in allocator proxy for pt21

dipu/torch_dipu/csrc_dipu/vendor/droplet/deviceimpl.cpp
allocator 随后会尝试释放一些 block 再 malloc，如果不清理错误，之后的调用全都会错误
=> fix(dipu,droplet): clear error after malloc failed (no mem)

.gitignore, dipu/QuickStart.md, dipu/scripts/ci/nv/ci_nv_env.sh, dipu/scripts/ci/nv/ci_nv_script.sh
删除了可能不再需要的 DIPU_ROOT 等环境变量，目前搜索了一下只有 DeepLinkExt 还在用这个，但那边应该不会使用 ci 的环境
另外为 @Wrench-Git 添加了一个样例，可以这样构建：
```bash
srun ...... bash scripts/ci/nv/ci_nv_script.sh build_dipu_dev -DDIOPI_TORCH_UNSAFE_BUILDATEN=ON
```
=> refactor(dipu): remove some maybe unused environment variables and add a dev mode into build script

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/tests/pytorch_config_cuda.py
std.correction_out的签名在不同的版本不一致，适配新版本时需要指定torch_ver，否则不会生成对应的算子代码
=> [DIPU]fix torch.std

dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp, dipu/torch_dipu/csrc_dipu/vendor/cuda/CUDACopyInplace.cpp
背景：沐熙设备上异步模式下跑模型时报错，只能同步模式下跑模型。
沐熙cat kernel里面分配了pin_memory 的tensor,并且用了copy算子。如果用了DIPU的allocator分配的pin_memory tensor,再用backend 为CUDA的copy，则不能正确处理tensor的生命周期，导致kernel异步计算时pin_memory的数据被修改（分给了其他tensor）,导致异步运行时报错，同步时没问题
DIPU_HOST_MEMCACHING_ALGORITHM=RAW 时该问题消失
详细记录：
https://aicarrier.feishu.cn/wiki/PXdYwcsjii9TJZk5AR1cG2bxnFd
=> fix async bug on muxi

dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py, dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/tests/python/unittests/test_mean_std.py, dipu/tests/pytorch_config_cuda.py, dipu/torch_dipu/csrc_dipu/diopirt/diopirt_impl.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUGeneratorImpl.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUGeneratorImpl.h, dipu/torch_dipu/csrc_dipu/vendor/cuda/CudaGeneratorImpl.cpp
1. 修复std算子
2. 更新diopi到最新，同时修复generator bug：generator set_state的时候更新seed和offset，否则seed、offset跟state不一致，test_generator.py测例过不了
=> Align diopiStd to device with torch version>=2.0

dipu/tests/python/unittests/test_generator.py, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUGeneratorImpl.cpp, dipu/torch_dipu/csrc_dipu/vendor/cuda/CudaGeneratorImpl.cpp
修复cuda generator bug，跟pytorch对齐，需要从最后16个字节获取seed和offset，而不是最开始16个字节
=> [DIPU]fix cuda generator set_state

dipu/torch_dipu/profiler/ascend/ascend_profiler_merger.py
在应用中发现ascend hardware event会出现重叠的错位情况
经问题定位，该问题是因为在做时间轴平移的时候，python float转换以及运算造成的精度损失
现将时间轴平移float相关计算转化成decimal
因考虑到decimal计算速度较慢，同时未发现剩余float计算对timeline结果的影响，因此只修改了关键部分的float计算。
=> fix ascend profiler timeline precision issue
