DeepLink-org/deeplink.framework

scripts/autogen_diopi_wrapper/diopi_wrapper_template.py
优化了autocompare：allclose打印误差mae，略微提高了精度要求，对比失败时显示compare_fail
=> autocompare_all_close_optimization

torch_dipu/csrc_dipu/runtime/core/guardimpl/DIPUGuardImpl.h
1. fix 了 DeviceGuard 返回错误流的问题，这个问题会导致 DDP 的   work->future_->markCompleted() 记录错误
=> fix loss fly

scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py, scripts/autogen_diopi_wrapper/diopi_functions.yaml, tests/test_ops/archived/test_ctc_loss.py
1. add ctc_loss operator for cambricon
=> Fuj/add ctc_loss for cambricon

torch_dipu/csrc_dipu/vendor/ascend/AscendGeneratorImpl.cpp
=> ascend support generator api

scripts/autogen_diopi_wrapper/diopi_functions.yaml, tests/test_ops/archived/test_prod.py
TESTED=python tests/test_ops/archived/test_prod.py
implemented #276
=> bind diopiProd to torch.prod

tests/test_ops/archived/test_rt_ddp.py, torch_dipu/csrc_dipu/runtime/core/DIPUEvent.cpp, torch_dipu/csrc_dipu/runtime/device/diclapis.h, torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.cpp, torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.h, torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.cpp, torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.h, torch_dipu/csrc_dipu/runtime/distributed/c10dOps.cpp, torch_dipu/csrc_dipu/vendor/ascend/communicatorimpl.cpp, torch_dipu/csrc_dipu/vendor/camb/cnrt_6.x/communiatorimpl.cpp, torch_dipu/csrc_dipu/vendor/cuda/communiatorimpl.cpp, torch_dipu/csrc_dipu/vendor/supa/commimpl.cpp, torch_dipu/csrc_dipu/vendor/topsrider/communiatorimpl.cpp
1. 增加了 p2p， reduce_scatter, reduce 等基本通信算子
=> enhance comm

dipu/torch_dipu/csrc_dipu/diopirt/diopirt_impl.cpp
see http://jdebp.info/FGA/reinterpret-cast-and-pointer-to-void.html
=> fix improper use of reinterpret_cast

dipu/scripts/ci/camb/ci_camb_script.sh, dipu/tests/run_camb_tests.sh, dipu/tests/test_ops/archived/test_rt_tensor.py, dipu/torch_dipu/__init__.py, dipu/torch_dipu/dipu/streams.py
=> recommit sync stream on new main

dipu/torch_dipu/csrc_dipu/CMakeLists.txt, dipu/torch_dipu/csrc_dipu/vendor/supa/CMakeLists.txt, dipu/torch_dipu/csrc_dipu/vendor/supa/copyinplace.cpp, dipu/torch_dipu/csrc_dipu/vendor/supa/deviceimpl.cpp, dipu/torch_dipu/csrc_dipu/vendor/supa/generatorimpl.cpp, dipu/torch_dipu/csrc_dipu/vendor/supa/vendorapi.h
fix compile failure of supa based on latest DIPU.
=> [FIX] fix compile failure of supa

dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp, dipu/torch_dipu/csrc_dipu/aten/ops/CopyKernel.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUCopyInplace.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUAsyncResourcePool.h, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBSCachingAllocator.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPURawAllocator.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPURawCachingAllocator.cpp, dipu/torch_dipu/csrc_dipu/vendor/cuda/CUDACopyInplace.cpp
1. Fixed bug in asynchronous mode
2. Optimized the logic of the cache when there is insufficient memory, reducing unnecessary overhead. This optimization will also fix the error of insufficient memory when allocating memory on Cambrian.
3. Added stream records to memory copy
=> fix cached-allocator async bug

.github/workflows/main.yml, dipu/scripts/ci/ascend/ci_ascend_env.sh, dipu/scripts/ci/ascend/ci_ascend_script.sh, dipu/scripts/ci/ci_one_iter.sh, dipu/scripts/ci/ci_run_one_iter.py, dipu/scripts/ci/test_one_iter_model_list.yaml, dipu/template_build_sh, dipu/tests/run_ascend_tests.sh
- Add a Build-PyTorch-For-Ascend job
- Add a Build-Ascend job
- Add a Test-Ascend job
- Add a Build-Ascend-Latest-Target job
- Add a Test-Ascend-Latest-Target job
- Add a Test-One-Iter-Ascend job
=> Add CI for Ascend

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/tests/test_ops/archived/test_prod.py, dipu/torch_dipu/testing/_internal/common_utils.py
affected ops: sum, cumsum, mean, prod, log_softmax
=> fix #311: ops not regarding dtype arg

.github/workflows/main.yml, dipu/CMakeLists.txt, dipu/QuickStart.md, dipu/scripts/ci/ascend/ci_ascend_script.sh, dipu/scripts/ci/camb/ci_camb_env.sh, dipu/scripts/ci/camb/ci_camb_script.sh, dipu/scripts/ci/nv/ci_nv_env.sh, dipu/scripts/ci/nv/ci_nv_script.sh, dipu/scripts/ci/topsrider/ci_topsrider_env.sh, dipu/scripts/ci/topsrider/ci_topsrider_script.sh, dipu/setup.py, dipu/template_build_sh
1. Supports automatic search for Python.h files, no longer need to explicitly set the PYTHON_INCLUDE_DIR environment variable
2. Supports automatically finding the pytorch path, no longer need to explicitly set the PYTHON_DIR environment variable when building
=> supports automatic search for Python.h files

.github/workflows/main.yml
是否可以考虑在所有 PR 上触发 CI，以方便堆叠 PR，在更小的粒度开发。
=> Let ci trigger for all PRs

dipu/tests/python/individual_scripts/test_op_benchmark.py, dipu/tests/python/unittests/test_amp.py, dipu/torch_dipu/csrc_dipu/aten/ops/DIPUAmp.cpp, dipu/torch_dipu/csrc_dipu/utils/helpfunc.cpp, dipu/torch_dipu/dipu/device.py, dipu/torch_dipu/dipu/generator.py, dipu/torch_dipu/dipu/storages.py
=> fix softmax cast

dipu/scripts/ci/test_one_iter_model_list.yaml
test ci_one_iter for detr(ascend)
=> test ci_one_iter for detr(ascend)

dipu/tests/python/individual_scripts/test_profiler_communication.py, dipu/tests/python/unittests/test_profiler_communication.py, dipu/torch_dipu/__init__.py, dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp, dipu/torch_dipu/csrc_dipu/profiler/profiler.cpp, dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.cpp, dipu/torch_dipu/profiler/profiler.py
1. 支持多机多卡profile
2. 修复不支持嵌套kernel event，导致cuda time统计错误bug
3. 修复跑resnet50模型时，开启了pin memory情况下，profile会出现core dump
=> enhence dipu profiler

dipu/scripts/ci/test_one_iter_model_list.yaml
Temporary comment out Ascend one iter.
=> Temporary comment out Ascend one iter.

dipu/CMakeLists.txt
add -f to avoid frequent SupportedDiopiFunctions.txt changes
=> add -f to avoid frequent SupportedDiopiFunctions.txt changes

dipu/torch_dipu/csrc_dipu/runtime/core/DIPUGeneratorImpl.h
Temporary support for PyTorch 2.1
=> Temporary support for PyTorch 2.1

dipu/CMakeLists.txt, dipu/pyproject.toml, dipu/scripts/ci/ascend/ci_ascend_script.sh, dipu/scripts/ci/camb/ci_camb_script.sh, dipu/scripts/ci/droplet/ci_droplet_script.sh, dipu/scripts/ci/nv/ci_nv_script.sh, dipu/scripts/ci/topsrider/ci_topsrider_script.sh, dipu/setup.py, dipu/third_party/CMakeLists.txt, dipu/torch_dipu/csrc_dipu/CMakeLists.txt
This PR's target is to enable users install DIPU by "pip install ."
THIS PR ASLO REQUIRE THE FOLLOWING CHANGE FOR thirdparty/kineto/libkineto/CMakeLists.txt
@caikun-pjlab 
`if(NOT DEFINED KINETO_COMPILED_WITH_CXX11_ABI)`
`  execute_process(`
`    COMMAND`
`      sh -x -c`
`      "python -c 'import torch;print(1 if torch.compiled_with_cxx11_abi() else 0)'"`
`    OUTPUT_VARIABLE KINETO_COMPILED_WITH_CXX11_ABI)`
`endif()`
=> One step install

dipu/third_party/CMakeLists.txt
fix: compile error when WITH_DIOPI isn't set
=> fix: compile error when WITH_DIOPI isn't set

dicp/readme.md, dipu/README.md
1. 增加dicp的readme文档；
2. DIPU中部分超链接更改
=> add dicp readme & update dipu reademe

dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py, dicp/dicp/vendor/AscendGraph/conversion.py
add stride and storage_offset for ascend output tensor
=> add stride and storage_offset for ascend output tensor

dipu/QuickStart.md
一键部署功能新增，因此更新DIPU教程文档。
相关更新的内容由李华懿提供～
=> Updateb DIPU QuickStart.md

dipu/setup.py
简单得重写了setup.py里设置DIPU_DEVICE的三行代码。
=> [minor] simplify the logic of getting DIPU_DEVICE in setup.py

dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/config.py, dicp/dicp/vendor/AscendGraph/conversion.py
=> feat: add dropout for ascend

dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/codegen/graph_utils.h
1. 去除图上不必要的输出(针对图上输入直接输出的情况)。
2. AscendOperator 增加对 ouput desc 的更新。
=> [dicp][ascend] remove inputs in graph outputs and enhance AscendOperator

dipu/torch_dipu/csrc_dipu/diopirt/diopirt_impl.cpp
=> [dipu] Fix dipu build err on tops.

dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocatorUtils.h, dipu/torch_dipu/csrc_dipu/runtime/core/guardimpl/DIPUGuardImpl.h
=> fix recycle dep

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/tests/python/unittests/test_ceil.py
add ceil.out.
add ceil.out  op: called by aten::add_.
=> fuj/ add ceil.out

dicp/dicp/vendor/AscendGraph/conversion.py
解决在910b上跑llama finetune出现的问题，对应相关issue：https://gitee.com/ascend/samples/issues/I8IGP8
=> [dicp][ascend]fix ascend mm/bmm

dicp/dicp/dynamo_bridge/operator.py, dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/infer_res_utils.py
finish more op's result inference
- "Reshape" has some problem to support "select" and "view" simultaneously.
=> [dicp][ascend]infer op resinfo_231204

.github/workflows/main.yml, dipu/scripts/ci/camb/ci_camb_env.sh, dipu/scripts/ci/nv/ci_nv_env.sh
=> update env python to 3.10

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/tests/python/unittests/test_conv2d.py
conv2d/backward的某些out的memory-format不对
=> [dipu]make conv2d's out in right memory-format

dicp/dicp/vendor/AscendGraph/codegen/fusion_switch.cfg, dicp/dicp/vendor/AscendGraph/codegen/graph_compile.cpp, dicp/dicp/vendor/AscendGraph/codegen/graph_utils.h, dicp/dicp/vendor/AscendGraph/compile_job.py
- Motivation and Context  背景
在dicp ascend 增加融合开关配置
- Description  描述  功能抽象
在dicp ascend 增加融合开关配置，默认开启所有融合算子
- 类别 （Bug 修复|new feature| Intenal SW ）
new feature
=> [dicp][ascend] feat: add fusion switch file for ascend

dipu/torch_dipu/csrc_dipu/profiler/profiler.cpp, dipu/torch_dipu/csrc_dipu/profiler/profiler.h
Reduced ~8% training time in torchvision ResNet-18 (batch_size=1).
=> [dipu] Speedup profiler ctor when not enabled

dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py, dicp/dicp/vendor/AscendGraph/conversion.py
在dicp ascend 去除不需要的broadcastTo
在dicp ascend 去除不需要的broadcastTo
new feature
=> [DICP]remove unnecessary broadcast

dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
在dicp ascend 优化inplace copy 性能，以及去除输入参数的拷贝
在dicp ascend 优化inplace copy 性能，以及去除输入参数的拷贝
new feature
=> [DICP] opt inplace copy

dipu/scripts/autogen_diopi_wrapper/diopi_wrapper_template.py, dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStream.cpp
yolov5 performance：73.8% -> 73.9%
=> [dipu] remove chech return value if

dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py, dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/scripts/autogen_diopi_wrapper/op_memory_format_converter.py, dipu/torch_dipu/csrc_dipu/CMakeLists.txt
This change will add a TAG in diopi_functions.yaml and the autogen will replace it with the prefered memory format depending on the convert_config.yaml of the device
=> Op preference mem format

.github/workflows/_runs-on-ascend.yml, dicp/scripts/ci/ascend/dipu_env.sh, dicp/scripts/ci/ascend/test_env.sh, dicp/test/ascend_scripts/models/static.ini, dicp/test/ascend_scripts/ops/static.ini
=> [dicp]add dicp ci for ascend

dipu/QuickStart.md
=> 【DIPU】Update QuickStart.md image

dicp/dicp/dynamo_bridge/operator.py, dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/conversion.py, dicp/dicp/vendor/AscendGraph/infer_res_utils.py
- add op view slice select
- fix bug in amax
- change log type to debug when ignoring inference failure
=> [dicp][ascend] infer op resinfo

.github/workflows/dicp.yml
=> disable dicp ci on dipu

dicp/dicp/vendor/AscendGraph/conversion.py
在dicp ascend 修复 sumdim/eq/lt 算子
在dicp ascend 修复 sumdim/eq/lt 算子
Bug 修复
=> [DICP]fix some ops in ascendgraph

dicp/dicp/vendor/TopsGraph/codegen/enflame.py, dicp/dicp/vendor/TopsGraph/config.py, dicp/dicp/vendor/TopsGraph/conversion.py, dicp/dicp/vendor/TopsGraph/tops_op.py, dicp/test/op/test_addmm.py, dicp/test/op/test_argmax.py, dicp/test/op/test_argmin.py, dicp/test/op/test_expand.py, dicp/test/op/test_index.py, dicp/test/op/test_sin.py, dicp/test/op/test_stack.py, dicp/test/op/test_unsqueeze.py, dicp/test/op/test_var_mean.py, dicp/test/tops_scripts/ops/static.ini
1.fix: index, embedding, hardswish_backward, expand, _softmax, addmm
2.support: stack, argmax, argmin, square
=> [dicp]fix and supoort some ops

dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py, dicp/dicp/vendor/AscendGraph/conversion.py, dicp/dicp/vendor/AscendGraph/infer_res_utils.py, dicp/test/ascend_scripts/models/run_test_models.sh, dicp/test/ascend_scripts/ops/run_test_ops.sh, dicp/test/ascend_scripts/ops/static.ini
- finish more ops' inference and running
- update corresponding tests
=> [dicp][ascend] infer op resinfo and run single op 231222

dipu/tests/python/individual_scripts/test_dipu_fallback.py, dipu/tests/python/individual_scripts/test_dumparg.py, dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUGeneratorImpl.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUGeneratorImpl.h
提升单文件测例覆盖度Line Coverage至50%以上
修改说明：https://aicarrier.feishu.cn/wiki/MrdZwS1agicNaDklK6LctunYnXg?create_from=copy_within_wiki&from=create_suite_copy&renamingWikiNode=false
=> [DIPU]Improve testing coverage

dipu/torch_dipu/csrc_dipu/runtime/core/DIPUGeneratorImpl.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/DIPUGeneratorImpl.h
还原覆盖度提升pr的部分修改，防止pytorch2.1下ci失败
=> [DIPU]Restore partial modifications of improving coverage

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/scripts/autogen_diopi_wrapper/diopi_wrapper_template.py, dipu/tests/python/unittests/test_mm.py, dipu/torch_dipu/csrc_dipu/aten/DIPUATenFunctions.h, dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp, dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.cpp, dipu/torch_dipu/csrc_dipu/aten/ops/EmptyOpsKernel.cpp, dipu/torch_dipu/csrc_dipu/aten/ops/NodispatchUtils.hpp, dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp, dipu/torch_dipu/csrc_dipu/aten/ops/PinMemoryKernel.cpp, dipu/torch_dipu/csrc_dipu/aten/ops/StorageShapeKernel.cpp, dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPURawAllocator.h, dipu/torch_dipu/csrc_dipu/utils/Log.h, dipu/torch_dipu/csrc_dipu/vendor/cuda/patch/wrapperRegister.cpp
mm [4, 4096]x[4096, 4096]: 39us -> 38us -> 36.1us
llama7b eval 123ms->121ms
plus some refactor and include cleaning
=> [dipu][optim] speedup mm by register dipu_mm and use nodispatch::empty

dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py
在dicp ascend 改写 add/adds 算子名称
在dicp ascend 改写 add/adds 算子名称
Bug 修复
=> [DICP]rename add/adds in ascend op

dicp/dicp/vendor/TopsGraph/codegen/enflame.py, dicp/dicp/vendor/TopsGraph/tops_op.py, dicp/scripts/ci/tops/ci_tops_build_env.sh, dicp/scripts/ci/tops/ci_tops_test_env.sh, dicp/test/common/accelerate_dynamo_backend.py, dicp/test/common/prompter.py, dicp/test/common/utils.py, dicp/test/model/run_test_model.sh, dicp/test/model/test_llama_finetune.py, dicp/test/tops_scripts/models/run_test_models.sh, dicp/test/tops_scripts/models/static.ini
1. Fix softmax match.
2. Set mock_cuda true.
3. Add llama_finetune test.
=> [DICP]Add llama_finetune test.

dicp/dicp/vendor/AscendGraph/conversion.py
修复llama finetune
修复llama finetune
Bug 修复
=> [DICP]fix llama finetune

dipu/FAQ.md
DIPU已经优化了代码，不会再出现这个错误，从FAQ文档里面删除
=> remove unuse item

dicp/test/ascend_scripts/models/run_test_models.sh
Fix ci if-else logic, fix pytest exit code bug.
=> [dicp][ascend]Fix ci if-else logic.

dipu/tests/python/individual_scripts/test_dipu_fallback.py
x = torch.empty(N, C, H, W) 有时候会返回带 nan 的tensor，导致assert失败，改为randn，同时执行100次，更容易发现偶现问题
=> [DIPU]fix test_dipu_copy_fallback empty nan

.github/workflows/_runs-on-ascend.yml, .gitignore, dicp/dicp/vendor/AscendGraph/compile_job.py
=> [dicp][ascend]zcx/optimize ci

dipu/torch_dipu/dipu/utils.py
Add AscendFormatTensor dispatch hook for format-convert error handling, to raise error for view-typed op.
=> [dipu]Add format_convert error handling hook.

dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/graph_utils.h, dicp/dicp/vendor/AscendGraph/codegen/utils.py, dicp/dicp/vendor/AscendGraph/conversion.py, dicp/dicp/vendor/AscendGraph/infer_res_utils.py, dicp/scripts/ci/ascend/dipu_env.sh
在dicp ascend 使用 get_const_proxy 来创建 const 算子
在dicp ascend 使用 get_const_proxy 来创建 const 算子
Bug 修复
=> [DICP]use get_const_proxy to construct const op

.github/workflows/main.yml
=> rm dicp ci in dipu workflow

dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/conversion.py, dicp/test/ascend_scripts/ops/static.ini, dicp/test/op/test_ge.py, dicp/test/op/test_logical_or.py, dicp/test/op/test_tril.py
在ascendgraph 中 ge/logical_or/repeat/tril 算子
在ascendgraph 中 ge/logical_or/repeat/tril 算子
new feature
=> [DICP]add ge/logical_or/repeat/tril for ascendgraph

dicp/dicp/dynamo_bridge/op_transformer.py, dicp/dicp/dynamo_bridge/utils.py, dicp/dicp/vendor/AscendGraph/ascend_op.py, dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/codegen/utils.py, dicp/dicp/vendor/AscendGraph/conversion.py
=> [dicp]zcx/add infer shape for matmul

.github/workflows/main.yml, dipu/scripts/ci/ascend/ci_ascend_script.sh
=> add ascend coverage

dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/opset_convert.py
ascend dicp support dipu native memory format
=> [dicp]zcx/dicp support dipu native memory format

dicp/dicp/dynamo_bridge/utils.py, dicp/dicp/vendor/AscendGraph/infer_res_utils.py, dicp/dicp/vendor/TopsGraph/conversion.py
Implement paras auto cast in some binary ops.
=> [DICP] Implement paras auto cast in some binary ops.

dipu/scripts/ci/ascend/ci_ascend_script.sh
=> feature: default ascend compilation in release

dicp/dicp/vendor/AscendGraph/conversion.py, dicp/test/model/test_hf.py, dicp/test/model/test_llama.py
在dicp ascend 去除不必要的 broadcastTo
在dicp ascend 去除不必要的 broadcastTo
Bug 修复
=> [DICP] remove unnecessary broadcast

dipu/torch_dipu/csrc_dipu/vendor/droplet/DropletGeneratorImpl.cpp
=> [DIPU] implement DROPLETGeneratorImpl

dicp/test/model/test_stable_diffusion.py
Modify stable diffusion decoder to pass ci.
=> [dicp][ascend]Fix stable diffusion ci result.

dicp/dicp/vendor/AscendGraph/conversion.py, dicp/test/op/test_index_put.py
在dicp ascend 修改 index_put 算子：当indices 为 bool  类型时，使用 masked_fill 算子实现。
在dicp ascend 修改 index_put 算子：当indices 为 bool  类型时，使用 masked_fill 算子实现。
Bug 修复
=> [DICP] update index_put

dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
fix steamWaitEvent by replacing aclrtSynchronizeEvent with aclrtStreamWaitEvent.
=> [dipu]yb/fix streamWaitEvent ascend

dipu/torch_dipu/csrc_dipu/vendor/ascend/AscendCopyInplace.cpp
=> [DIPU] Remove unnecessary sync in copyPostProcess for Ascend

dipu/scripts/ci/test_one_iter_traditional_model_list.yaml
=> tyf/change DIOPI

dipu/tests/python/individual_scripts/test_op_benchmark.py
=> zsk/update submoudle DIOPI

dipu/torch_dipu/dipu/__init__.py, dipu/torch_dipu/dipu/memory.py, dipu/torch_dipu/dipu/nvtx.py, dipu/torch_dipu/utils/deepspeed_dipu/README.md, dipu/torch_dipu/utils/deepspeed_dipu/__init__.py, dipu/torch_dipu/utils/deepspeed_dipu/deepspeed_patch.py
Patch some functions so that we can use deepspeed in dipu like the following code.
import torch_dipu.utils.deepspeed_dipu
=> the initial commit of support deepspeed in dipu

dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
=> [DIPU] Remove unnecessary sync in CopyAll

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
=> [DIPU] Add index.Tensor schema

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
=> [DIPU] Add _foreach_lerp_.Scalar schema

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
=> zzf/fix bug of embedding_backward

dipu/SupportedDiopiFunctions.txt, dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctions.hpp
optimize impl to avoid redundant dispatch for performance:
1. add bmm schema
2. add tiru_ and triu schema
=> [Ascend] fuj / optimize bmm and triu

dipu/SupportedDiopiFunctions.txt, dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
update nll_loss and nll_loss_backward schema
NOTE: dependency code https://github.com/DeepLink-org/DIOPI/pull/1095
=> feat(dipu): update nll_loss and nll_loss_backward schema for ascend

dipu/SupportedDiopiFunctions.txt, dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/tests/python/unittests/test_linalg_vec_norm.py, dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
1. dispatch aten::linalg_vector_norm to diopiLinalgVecNorm
2. add test case of aten::linalg_vector_norm for ascend
3. fix infer_reduce_op_shape for keepdim=True when dim given None
=> [Ascend] fuj / linalg-vec-norm

dipu/SupportedDiopiFunctions.txt, dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py, dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml, dipu/tests/python/unittests/test_equal.py
=> [Ascend]zzf/add equal op

dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
run dipu without "custom fallback ……" display.
=> zzf/ disable fallback op info display

dipu/tests/python/unittests/test_load.py, dipu/torch_dipu/dipu/storages.py
Minimal reproduce:
```python
import torch
import torch_dipu
t = torch.randn(3, 3).cuda()
torch.save(t, "a.pt")
print("Save tensor successfully", end="\n\n")
t = torch.load("a.pt")
print("Load tensor successfully")
```
=> fix(dipu): Bug in loading tensor

dipu/CMakeLists.txt, dipu/scripts/autogen_diopi_wrapper/autogen_wrapped_code.sh, dipu/torch_dipu/csrc_dipu/CMakeLists.txt
* fix the dependency of codegen
* use release mode as default and fix the problem that can't compile as a debug model.
=> fix(dipu): resolve several CMake problems

dicp/dicp/vendor/AscendGraph/conversion.py
修复 get_shape_proxy 函数
考虑 `shape` 为  `[1, s8, ((s9//s11)//s81)]`  类似这种情况时，原有代码逻辑处理 `s8` 时候，会将 `s81` 也部分替换掉。
即 `dim_str = dim_str.replace(elem, replace_str)` 这里不应该对原有字符进行 `s8` 匹配替换，而是应该替换 `preprocess_expression` 后的 `elems` ，最后再重新组装。
Bug 修复
=> [DICP] fix get_shape_proxy

dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
add getDeviceStatus() implmention for ascend.
=> [dipu]zcx/add memory status impl for ascend

dipu/tests/python/individual_scripts/test_rt_ddp.py, dipu/torch_dipu/csrc_dipu/runtime/device/diclapis.h, dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.cpp, dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.h, dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.cpp, dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.h, dipu/torch_dipu/csrc_dipu/runtime/distributed/c10dOps.cpp, dipu/torch_dipu/csrc_dipu/vendor/ascend/communicatorimpl.cpp, dipu/torch_dipu/csrc_dipu/vendor/camb/cnrt_6.x/communiatorimpl.cpp, dipu/torch_dipu/csrc_dipu/vendor/cuda/communiatorimpl.cpp, dipu/torch_dipu/csrc_dipu/vendor/droplet/communicatorimpl.cpp, dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/communicatorimpl.cpp, dipu/torch_dipu/csrc_dipu/vendor/supa/commimpl.cpp, dipu/torch_dipu/csrc_dipu/vendor/topsrider/communiatorimpl.cpp
- Done
- Implement all_to_all_single with equal splits
- TODO or maybe in next PR
- Implement all_to_all_single with unequal splits
- Implement nccl group calls for all-to-all
- Implement all_to_all
=> [DIPU] Implement all_to_all_single

.github/workflows/main.yml
=> Fix Ascend CI

dipu/tests/python/individual_scripts/test_allocator_conf.py, dipu/torch_dipu/__init__.py, dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp, dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingDeviceAllocator.cpp, dipu/torch_dipu/dipu/memory.py
plus: refactor/simplify some pybind code
=> feat(dipu): mock torch.cuda.memory._set_allocator_settings

dicp/dicp/vendor/AscendGraph/codegen/ascend.py, dicp/dicp/vendor/AscendGraph/codegen/ge_builder.h, dicp/dicp/vendor/AscendGraph/codegen/ge_builder_config.json, dicp/dicp/vendor/AscendGraph/codegen/ge_graph.h, dicp/dicp/vendor/AscendGraph/codegen/ge_init_config.json, dicp/dicp/vendor/AscendGraph/codegen/ge_runner.h, dicp/dicp/vendor/AscendGraph/codegen/graph_compile.cpp, dicp/dicp/vendor/AscendGraph/codegen/graph_utils.h, dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py, dicp/dicp/vendor/AscendGraph/codegen/utils.py, dicp/dicp/vendor/AscendGraph/compile_job.py
使用 ge graph run 相关接口
使用 ge graph run 相关接口
new feature
=> [DICP] use ge graph runner for ascendgraph

dipu/tests/python/unittests/test_profiler_vendor.py
=> test(dipu): update test_profiler_vendor.py in corresponding to DIOPI changes

dipu/torch_dipu/csrc_dipu/vendor/cuda/communiatorimpl.cpp
=> maca_enable_nccl_bf16

dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
Solve the problem of not being able to exit gracefully.
Just for BFCachingAllocator。
=> [dipu][allocator] Solve the problem of not being able to exit gracefully

dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp, dipu/torch_dipu/csrc_dipu/utils/Log.h
Optimized the prompt information for users when setting CPU affinity
优化了设置cpu亲和性时对用户的提示信息
=> Optimized the prompt information for users when setting CPU affinity

dipu/tests/pytorch_config_muxi.py
在test/pytorch_config_muxi中手动调用了pytorch_config_cuda中的模块
=> fix(dipu): Modifies the problem of reusing pytorch _ config _ cuda in tests / pytorch _ config _ muxi

dipu/tests/python/unittests/test_nll_loss.py
fix and add test for nll_loss with neg ignore_index
see also https://github.com/DeepLink-org/DIOPI/pull/1161
=> fix(dipu): nll_loss with neg ignore_index

dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBSCachingAllocator.cpp
修复 异步资源  "No ready resource to get!"  的bug
=> fix bs allocator bug

dipu/torch_dipu/csrc_dipu/vendor/droplet/communicatorimpl.cpp, dipu/torch_dipu/csrc_dipu/vendor/droplet/vendorapi.h
支持在没有 PCCL 的情况下，通过 memcpy 模拟 PCCL 的单卡通信。
=> feat(dipu,droplet): simulate 1-card PCCL communication using memcpy

dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
add _foreach_mul_.Tensor schema
ref: https://github.com/pytorch/pytorch/blob/v2.1.0/aten/src/ATen/native/native_functions.yaml#L10112C1-L10127C1
=> add _foreach_mul_.Tensor schema

dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp, dipu/torch_dipu/csrc_dipu/diopirt/diopirt_impl.cpp, dipu/torch_dipu/csrc_dipu/vendor/cuda/CUDACopyInplace.cpp
this change will accerate the aten::copy by about 5%.
=> Faster copy

dipu/setup.py
=> refactor(dipu): better setup.py

dipu/torch_dipu/__init__.py
dipu不支持jit，对jit进行了patch
jit patch可能导致模型训练的精度有细微差别，因此需要打印对应的log。
=> feat(DIPU): add log for jit patch

dicp/setup.py
修复dicp的CI跑不通问题，删除torch_dipu==0.1
=> fix(dicp): fix dicp test on ci

dipu/scripts/ci/droplet/ci_droplet_script.sh
1. 构建模式是 Debug，坑了 S2 的性能分析好久，改成 Release
2. 有个莫名其妙的 `git checkout .`，极其危险，把我写的代码都搞没了，删掉
=> build(dipu,droplet): fix some ridiculous parts in build script
